%% This script loads into memory some outputs generated by Fortran 
% and perform some analysis (plot, statistics, etc.)


clear; clc; close all

%Directory where txt files generated by Fortran are located
TxtDir = 'IncomeFluctuationProblem\output';

%Current directory where this M-file is stored
CurDir = pwd;

cd(TxtDir)

%Read txt into Matlab
%Parameters
constants = load('constants.txt');
beta      = constants(1);
r         = constants(2);
b         = constants(3);
valtol    = constants(4);
maxiter   = constants(5);

%Arrays
z_vals     = load('z_vals.txt');
asset_grid = load('asset_grid.txt');
TV_vec     = load('TV.txt');
c_pol_vec  = load('c_pol.txt');
a_pol_vec  = load('a_pol.txt');


%Reshape arrays if needed
nz    = length(z_vals);
na    = length(asset_grid);
TV    = reshape(TV_vec,[na,nz]);
c_pol = reshape(c_pol_vec,[na,nz]);
a_pol = reshape(a_pol_vec,[na,nz]);

%Plot optimal savings with 45 degree line
figure(1)
plot(asset_grid,a_pol(:,1),'linewidth',2)
hold on 
plot(asset_grid,a_pol(:,2),'linewidth',2)
hold on 
plot(asset_grid,asset_grid,'--','linewidth',2)
legend('Low income','High income','45 line','Location','NorthWest')
xlabel('Current assets')
ylabel('Next period assets') 
title('Savings Policy Function')
grid on
hold off

%Plot optimal consumption
figure(2)
plot(asset_grid,c_pol(:,1),'linewidth',2)
hold on 
plot(asset_grid,c_pol(:,2),'linewidth',2)
hold on 
legend('Low income','High income','Location','NorthWest')
xlabel('Current assets')
ylabel('Consumption') 
title('Consumption Policy Function')
grid on
hold off

%Go back to initial folder where this M-file is stored
cd(CurDir)

